### ISSUE TITLE
Using as View

### ISSUE THREAD

**Issue by KVinS** [yukuku/ambilwarna#11]
There is no possibility to use the library, and a View? For example, a color change in real time.
![screenshot_2015-10-13-00-45-51](https://cloud.githubusercontent.com/assets/3009807/11308125/6b9d30e6-8fcd-11e5-944c-e2f2a17a5fcf.png)

**Comment by denisk20** [comment]
This is definitely possible. Take a look at [AmbilWarnaSquare](https://github.com/yukuku/ambilwarna/blob/master/library/src/main/java/yuku/ambilwarna/AmbilWarnaSquare.java) class which is used in the Dialog. Implementing colored rings from your example will be a bit more tricky, but will likely to follow the same principle.

**Comment by KVinS** [comment]
Now I look at the source code and trying to understand it. 
That would be some View (viewCursor, viewHue...), instead of one? I only used onDraw method, but you use the same drawable and LayoutInflater. 
I am a beginning developer. I do not understand why you do not use drawCircle and other methods of drawing?

https://gist.github.com/KVinS/f79f8575cd3b5e1b922b

**Comment by denisk20** [comment]
It depends on your needs. If I understand correctly you want to define 4-color palette on the left and then somehow fill 3 rings and 1 circle with gradients based on that colors and make these circles touchable so that a user is able to pick a color from them. If so then you can use a view similar to [AmbilWarnaPrefWidgetView](https://github.com/yukuku/ambilwarna/blob/master/library/src/main/java/yuku/ambilwarna/widget/AmbilWarnaPrefWidgetView.java) for the squares and use [AmbilWarnaDialog](https://github.com/yukuku/ambilwarna/blob/master/library/src/main/java/yuku/ambilwarna/AmbilWarnaDialog.java) as an example for the rings. The rings will be more complex than a plain gradient square I guess, however still possible. And you can totally use `onDraw` method to implement them.

**Comment by KVinS** [comment]
Oh no. I want to insert your picker instead of rings picker.

**Comment by KVinS** [comment]
I want to do something. But "viewSatVal.setHue" private =(
![screenshot_2015-11-20-23-40-23 1](https://cloud.githubusercontent.com/assets/3009807/11311359/6e867458-8fe0-11e5-80bf-eb54f83d4c26.png)

**Comment by KVinS** [comment]
It was necessary to integrate the library module and rewrite a little skin. But I am satisfied with the result =) Only slowly drawing (
![screenshot_2015-11-21-17-58-42 1](https://cloud.githubusercontent.com/assets/3009807/11319049/e538c462-907a-11e5-921c-a5cccd525c89.png)
![screenshot_2015-11-21-17-58-49](https://cloud.githubusercontent.com/assets/3009807/11319050/e53a66f0-907a-11e5-85ce-300d1e622b3a.png)

**Comment by denisk20** [comment]
Nice job! For performance profiling I would recommend to start with Android Studio allocation tracker:
http://android-developers.blogspot.com/2015/07/get-your-hands-on-android-studio-13.html
If GPU is the bottleneck then you can profile it on a device or emulator, instructions are, for example,  here:
https://www.youtube.com/watch?v=VzYkVL1n4M8

**Comment by SolaBe** [comment]
I want create my own DialogFragment with two tabs - grid colors and color picker. Can i you your code in my project? 
я хочу написать свой DialogFragment с двумя вкладками - таблица цветов и пикер. Могу я использовать часть кода в своем проекте?

**Comment by denisk20** [comment]
The code is licensed under Apache 2 license, so do whatever you want.
