### ISSUE TITLE
changing the size

### ISSUE THREAD

**Issue by djsbaa** [yukuku/ambilwarna#26]
How do I change the AmbilWarnaDialog size to fit the whole screen ??

**Comment by denisk20** [comment]
Not without some refactoring. We currently put everything into `android.app.AlertDialog`. Take a look at `AmbilWarnaDialog` constructor:
https://github.com/yukuku/ambilwarna/blob/master/library/src/main/java/yuku/ambilwarna/AmbilWarnaDialog.java#L59
It basically creates a view and sets it as a root view for AlertDialog. You can use similar code to construct the same view and show it the way you like.

**Comment by djsbaa** [comment]
Please, Can you Explain more for me ;)

**Comment by denisk20** [comment]
If you follow the link that I have posted you'll find code which creates color picker and puts it into the dialog. Dialogs can't span whole screen as far as I know, so you'll need to extract this code and use the view which it provides. Something like

```
/*
This will include roughly https://github.com/yukuku/ambilwarna/blob/master/library/src/main/java/yuku/ambilwarna/AmbilWarnaDialog.java#L70-L172
*/
View getPickerView() {...}
//in your activity
View pickerView = getPickerView();
((ViewGroup) findViewBy(R.id.your_container_id)).addChild(pickerView);
```

This implies that you have a container view pre-defined so that it spans the whole screen.
