### ISSUE TITLE
Diff View of ColorPicker

### ISSUE THREAD

**Issue by GauravCreed** [yukuku/ambilwarna#30]
Hi @yukuku 

i just notice that view of displaying color picker id diff in mobile device and tablet,

Here is the tablet view.
![device-2017-12-20-183719](https://user-images.githubusercontent.com/13447384/34208788-b034be14-e5b5-11e7-9ae0-fa456c1b6d17.png)

and my mobile device the color picker look like..
![device-2017-12-20-183749](https://user-images.githubusercontent.com/13447384/34208827-cf619690-e5b5-11e7-9c02-9f56171bb707.png)

as you can see in both screenshot, the right side color change panel is not display in mobile device, idont't why this is happening, is ther any solution for this, then please help me.

Thanks(_)

**Comment by denisk20** [comment]
Hi, which mobile device are you testing on?

**Comment by GauravCreed** [comment]
Hey @yukuku 

Thanks for the respone.

My Mobile device is : Nexus 5 :  Api - 26 and
My Tablet device is : MiPad 4.4.4

**Comment by denisk20** [comment]
Which resolution your nexus 5 is? (I assume it's an emulator because of API 26).
I have checked on standard nexus 5 emulator which is 1080 x 1920 and the dialog looks fine
![image](https://user-images.githubusercontent.com/3080318/34357146-336f0ba4-ea4d-11e7-8e6a-badd5333b1cf.png)
I was able to get a trimmed dialog only when testing on emulator with 480 x 800 but only when displaying the dialog along with the alpha slider:
![image](https://user-images.githubusercontent.com/3080318/34357207-c1c3a07c-ea4d-11e7-84df-3040fae75242.png)
Not sure if we'll ever support resolutions that tiny.

**Comment by GauravCreed** [comment]
Hmmmm...

this is same issue i have , is there any solution for that???

Thanks.

**Comment by denisk20** [comment]
is this a real-life issue for you? Do you really need to support such tiny devices? I don't think we'll add support but you can contribute it if you need it.

**Comment by GauravCreed** [comment]
I did not check any small devices but i check in android emulator, that is the why i open a new issue.

if it is not supported in a small device then you can close this issue.
