### ISSUE TITLE
Propose new logo

### ISSUE THREAD

**Issue by anaufalm** [yukuku/ambilwarna#35]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by denisk20** [comment]
@anaufalm Hello, why don't you post it here ))

**Comment by anaufalm** [comment]
Here is your logo, hope you like it. If there is any suggestion or revision, feel free to comment. I'll be happy to fix it. I'll send you mail for complete files. :)

Construction:
![ambilwarna-construction](https://user-images.githubusercontent.com/35919168/39116561-f9b573ca-470e-11e8-867a-4d4e93e85c2d.png)

**Logomark:**
![ambilwarna-logomark](https://user-images.githubusercontent.com/35919168/39116450-b0f99a1c-470e-11e8-9e0d-320a5fcd133e.png)

**Logotype: (1, 2, 3)**
![ambilwarna-logotype](https://user-images.githubusercontent.com/35919168/39116482-c3ac5a00-470e-11e8-9428-049608d3b75e.png)

![ambilwarna-logotype2](https://user-images.githubusercontent.com/35919168/39116496-cd3475e4-470e-11e8-9c92-72c2898b73c4.png)

![ambilwarna-logotype3](https://user-images.githubusercontent.com/35919168/39116515-db739aae-470e-11e8-9a4f-8a780681868c.png)

Logo meaning:
![ambilwarna-mean](https://user-images.githubusercontent.com/35919168/39116788-82022070-470f-11e8-8f94-3397fb139254.png)

COLOR VERSION:

Light version:
![ambilwarna-color-logomark-light](https://user-images.githubusercontent.com/35919168/39116825-960e68e4-470f-11e8-9276-be15df1950be.png)

![ambilwarna-color-logotype-light](https://user-images.githubusercontent.com/35919168/39116877-b7508adc-470f-11e8-89e6-4d8a3496fe77.png)

Dark version:
![ambilwarna-color-logomark-dark](https://user-images.githubusercontent.com/35919168/39116888-c1dfa71c-470f-11e8-83ea-a592598d5b9f.png)

![ambilwarna-color-logotype-dark](https://user-images.githubusercontent.com/35919168/39116905-cab98862-470f-11e8-9cc4-795004697294.png)

Single color:
![ambilwarna-color-logomark-single](https://user-images.githubusercontent.com/35919168/39116934-d86f3f10-470f-11e8-9de6-aab368ddfeeb.png)

App Icon:
![ambilwarna-icon](https://user-images.githubusercontent.com/35919168/39116955-e8b81194-470f-11e8-8b21-6d48300af400.png)

Other Version:
![ambilwarna-other](https://user-images.githubusercontent.com/35919168/39117045-2078e18a-4710-11e8-822f-4b49da165ef7.png)

**Comment by denisk20** [comment]
Wow, this is very well-thought and looks fantastic, great job! I like the blue color version the most ))
![image](https://user-images.githubusercontent.com/3080318/39118081-1fb3ad44-46f1-11e8-8bbe-d36cdd7ab36e.png)
One thought: maybe we should drop the first small "A" letter and let the big "A" also serve as the first letter of the name? Otherwise it feels a bit like A**a**mbilwarna )) Or it may be just my perception.

It is @yukuku to make the final decision since I'm not the owner of the project ))

**Comment by anaufalm** [comment]
Therefore I make the third logotype option. ;)

Or in first **a** letter needs to be enlarged? Just little maybe. What do you think?

Like this:
![ambilwarna-logotype4](https://user-images.githubusercontent.com/35919168/39119308-b3d09554-4715-11e8-8499-543293ac126a.png)

**Comment by anaufalm** [comment]
other colors:
![ambilwarna-logotype5](https://user-images.githubusercontent.com/35919168/39119389-ec063faa-4715-11e8-8cf3-8328c90576b4.png)

**Comment by denisk20** [comment]
Yes, a bit enlarged so that the first **a** stands out a bit, I think. Thank you, it looks great!

**Comment by anaufalm** [comment]
I'll be happy if this logo used. You can use it, coz this logo licensed under CC BY, you can put my name as a contributor in readme or etc. Thanks :)

Cc: @yukuku

**Comment by denisk20** [comment]
Absolutely, if @yukuku gives green light I'll create a pull request and your name will stay in readme forever ))

**Comment by yukuku** [comment]
@denisk20 yes sure!  This logo is very nice and polished. Thank you @anaufalm !

**Comment by denisk20** [comment]
Hey @anaufalm , I'm preparing a pull request to include all bits for the new logo, wanted to ask if you can send us a set of app icons similar to this, I want to use them as our demo app icon
![](https://user-images.githubusercontent.com/35919168/39116955-e8b81194-470f-11e8-8b21-6d48300af400.png)
but with this icon
![image](https://user-images.githubusercontent.com/3080318/39193310-eba02afc-47e3-11e8-9d76-80e97a5cd946.png)

(I was thinking of using this logo, with blue first "A" letter)
![image](https://user-images.githubusercontent.com/3080318/39193399-2303c882-47e4-11e8-82d6-e6d67d7bdfc8.png)

If you just archive the icons as separate files I'll appreciate it since I'm very bad at graphics and manually cutting the icons can probably take me the whole day ))

**Comment by anaufalm** [comment]
Here is your [package](https://drive.google.com/open?id=1QEXn7xZ1VdDFCBEG_EUrcwscdGOClpBB) @denisk20. 

Saya juga tambahkan format svg untuk scalable image jika sewaktu-waktu ingin menginginkan gambar yang lain dengan ukuran yang berbeda. Anda dapat mengeditnya langsung. :)

**Comment by denisk20** [comment]
@anaufalm @yukuku I've made changes in this branch

https://github.com/yukuku/ambilwarna/tree/new-logo

Isn't the logo in README too big? Maybe change the position? If it's OK I can merge that.

**Comment by anaufalm** [comment]
I think thats to big. Looks funny.

I recommend to use this one, this is specially for readme header and you can put to center. :)
![ambilwarna-header](https://user-images.githubusercontent.com/35919168/39242691-2446d96a-48b5-11e8-8b51-c052664f23eb.png)

*I put this image in gdrive folder before.

**Comment by denisk20** [comment]
@anaufalm how about now? I haven't found a cropped image in gdrive so I have manually re-sized the current one; also haven't put to center, seems to look good?

**Comment by anaufalm** [comment]
Awesome, looks better now. :)

Btw this is the image:
https://drive.google.com/open?id=1hU-hGJb3J8UQNSHLnslv4ZM0J-HRwsVy

**Comment by denisk20** [comment]
I have rebased everything nicely and created a pull request:

https://github.com/yukuku/ambilwarna/pull/38

**Comment by anaufalm** [comment]
Thank you so much @denisk20

**Comment by denisk20** [comment]
merged.
